name: Lint

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  lint:
    name: Lint Code
    runs-on: ubuntu-latest

    env:
      WORKING_DIR: sqlite # 将其更改为您的Rust项目名称

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Rust
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true

      - name: Check Format
        run: cargo fmt -- --check
        working-directory: ${{ env.WORKING_DIR }}

      - name: Run Clippy
        run: cargo clippy -- -D warnings
        working-directory: ${{ env.WORKING_DIR }}
